this.examples=[
	{
		"name": "Universitaetschema",
		"description": "Das bekannte Schema.",
		"source": "&Uml;bung zur Vorlesung",
		"ruleset": [
			"%%voraussetzen(VorgNr,NachfNr)",
			"voraussetzen(5001,5041).",
			"voraussetzen(5001,5043).",
			"voraussetzen(5001,5049).",
			"voraussetzen(5041,5216).",
			"voraussetzen(5043,5052).",
			"voraussetzen(5041,5052).",
			"voraussetzen(5052,5259).",
			"%%vorlesungen(VorlNr, Titel, SWS, gelesenVon)",
			"vorlesungen(5001,grundzuege,4,2137).",
			"vorlesungen(5041,ethik,4,2125).",
			"vorlesungen(5043,erkenntnistheorie,3,2126).",
			"vorlesungen(5049,maeeutik,2,2125).",
			"vorlesungen(4052,logik,4,2125).",
			"vorlesungen(5052,wissenschaftstheorie,3,2126).",
			"vorlesungen(5216,bioethik,2,2126).",
			"vorlesungen(5259,der_wiener_kreis,2,2133).",
			"vorlesungen(5022,glaube_und_Wissen,2,2134).",
			"vorlesungen(4630,die_3_kritiken,4,2137).",
			"%%hoeren(MatrNr,VorlNr)",
			"hoeren(26120,5001).",
			"hoeren(27550,5001).",
			"hoeren(27550,4052).",
			"hoeren(28106,5041).",
			"hoeren(28106,5052).",
			"hoeren(28106,5216).",
			"hoeren(28106,5259).",
			"hoeren(29120,5001).",
			"hoeren(29120,5041).",
			"hoeren(29120,5049).",
			"hoeren(29555,5022).",
			"hoeren(25403,5022).",
			"hoeren(29555,5001).",
			"%%professoren(PersNr,Name,Rang,Raum)",
			"professoren(2125,sokrates,C4,226).",
			"professoren(2126,russel,C4,232).",
			"professoren(2127,kopernikus,C3,310).",
			"professoren(2133,popper,C3,52).",
			"professoren(2134,augustinus,C3,309).",
			"professoren(2136,curie,C4,36).",
			"professoren(2137,kant,C4,7).",
			"%%pruefen(MatrNr,VorlNr,PersNr,Note)",
			"pruefen(28106,5001,2126,1).",
			"pruefen(25403,5041,2125,2).",
			"pruefen(27550,4630,2137,2).",
			"pruefen(25403,4630,2137,2).",
			"%%assistenten(PersNr, Name, Fachgebiet, Boss)",
			"assistenten(3002,platon,ideenlehre,2125 ).",
			"assistenten(3003,aristoteles,syllogistik,2125).",
			"assistenten(3004,wittgenstein,sprachtheorie,2126).",
			"assistenten(3005,rhetikus,planetenbewegung,2127).",
			"assistenten(3006,newton,keplersche_gesetze,2127).",
			"assistenten(3007,spinoza,gott_und_natur,2134).",
			"%%studenten(MatrNr, Name, Semester)",
			"studenten(24002,xenokrates,18).",
			"studenten(25403,jonas,12).",
			"studenten(26120,fichte,10).",
			"studenten(26830,aristoxenos,8).",
			"studenten(27550,schopenhauer,6).",
			"studenten(28106,carnap,3).",
			"studenten(29120,theophrastos,2).",
			"studenten(29555,feuerbach,2)."
		],
		"query": "studenten(MATRNR,NAME,SEMESTER)"
	},
	{
		"name": "Kind - Eltern (griechische Goetter und Helden)",
		"description": "Ein einf%uuml;hrendes Beispiel zur Rekursion in Datalog.",
		"source": "&Uml;bung zur Vorlesung",
		"ruleset": [
			"kindEltern(zeus,leto,apollon).",
			"kindEltern(zeus,leto,artemis).",
			"kindEltern(zeus,maia,hermes).",
			"kindEltern(koios,phoebe,leto).",
			"kindEltern(atlas,pleione,maia).",
			"kindEltern(kronos,rheia,hades).",
			"kindEltern(kronos,rheia,poseidon).",
			"kindEltern(kronos,rheia,zeus)."
		],
		"query": "kindEltern(zeus,leto,KIND)"
	},
	{
		"name": "Segler-Boots-Reservierung",
		"description": "Schon gesegelt?",
		"source": "&Uml;bung zur Vorlesung",
		"ruleset": [
			"%segler(SID,SNAME,EINSTUFUNG,ALTER)",
			"segler(0,alex,10,39).",
			"segler(1,alex,10,28).",
			"segler(2,max,6,35).",
			"segler(3,corinna,10,28).",
			"segler(4,josef,10,28).",
			"segler(5,dennis,10,28).",
			"segler(6,michael,10,28).",
			"segler(7,moritz,10,28).",
			"segler(8,sergiu,10,28).",
			"segler(9,'Lubber',7,19).",
			"segler(10,'Horatio',8,14).",
			"%boot(BID,BNAME,FARBE)",
			"boot(100,ferry,red).",
			"boot(101,sun,red).",
			"boot(102,river,blue).",
			"boot(103,ocean,blue).",
			"boot(104,submarine,yellow).",
			"boot(105,beach,yellow).",
			"boot(106,swan,black).",
			"boot(107,nighty,black).",
			"boot(108,bride,white).",
			"boot(109,duck,white).",
			"boot(110,golf,green).",
			"boot(111,frog,green).",
			"%reservierung(SID,BID,DATUM)",
			"reservierung(2,100,20180430).",
			"reservierung(2,103,20180428).",
			"reservierung(1,101,20180430).",
			"reservierung(4,102,20180430).",
			"reservierung(3,103,20180430).",
			"reservierung(5,104,20180430).",
			"reservierung(6,105,20180430).",
			"reservierung(7,106,20180430).",
			"reservierung(8,107,20180430).",
			"reservierung(2,108,20180429).",
			"reservierung(9,110,20180429).",
			"reservierung(9,111,20180430).",
			"reservierung(10,111,20180429).",
		],
		"query": "segler(SID,SNAME,EINSTUFUNG,ALTER)"
	},
	{
		"name": "Umlaufbahnen von kosmologischen Objekten",
		"description": "Umlaufbahnen von kosmologischen Objekten",
		"source": "Rafael Caballero-Rold\u0027an, 2007",
		"ruleset": [
			"% Orbits of cosmological objects",
			"% Rafael Caballero-Rold\u0027an, 2007",
			"",
			"star(sun).",
			"",
			"orbits(earth, sun).",
			"orbits(moon, earth).",
			"orbits(X,Y) :-", 
			"  orbits(X,Z), ",
			"  orbits(Z,Y). % This is correct",
			"%  orbits(Y,Z). % This is an error",
			"",
			"satellite(X,Y) :-",
			"  orbits(X,Y),",
			"  not(intermediate(X,Y)),", 
			"  not(star(Y)).",
			"",
			"planet(X) :-", 
			"  orbits(X,Y),", 
			"  star(Y),", 
			"  not(intermediate(X,Y)).",
			"",
			"intermediate(X,Y) :-", 
			"  orbits(X,Z), ",
			"  orbits(Z,Y). % This is correct",
			"%  orbits(Y,Z). % This is an error"
		],
		"query": "satellite(X,earth)"
	},
	{
		"name": "Pfade in einem Graphen",
		"description": "Ein einf%uuml;hrendes Beispiel zur Rekursion in Datalog.",
		"source": "Datalog Educational System - User's Manual",
		"ruleset": [
			"% Paths in a Graph",
			"edge(a,b).",
			"edge(a,c).",
			"edge(b,a).",
			"edge(b,d).",
			"",
			"path(X,Y) :- path(X,Z), edge(Z,Y).",
			"path(X,Y) :- edge(X,Y)."
		],
		"query": "path(X,Y)"
	},
	{
		"name": "Computer Parts",
		"description": "Teile eines Rechners.",
		"source": "http://people.inf.elte.hu/sila/DB1English/exercise06_products.pdf",
		"ruleset": [
			"ModelParts(workstation,mainboard-hl7).",
			"ModelParts(workstation,hdd30g).",
			"Part(mainboard-hl7,asuz).",
			"Part(gpu7700,nvidio).",
			"Part(hdd30g,sealgate).",
			"Part(transistor,foxcom).",
			"Part(motor,enginesUnited).",
			"Part(wire,theWireCompany).",
			"Part(magnet,theMagnetCompany).",
			"ConsistsOf(hdd30g,transistor).",
			"ConsistsOf(hdd30g,motor).",
			"ConsistsOf(motor,wire).",
			"ConsistsOf(motor,magnet)."
		],
		"query": "ModelParts(A,B)"
	},
	{
		"name": "Muencher U-Bahn (U1, U2, U3, U4, U5 und U6)",
		"description": "Teile des Muenchner U-Bahn-Netzes.",
		"source": "",
		"ruleset": [
			"% U1",
			"direkt(olympia_einkaufszentrum,georg_brauchle_ring,u1).",
			"direkt(georg_brauchle_ring,westfriedhof,u1).",
			"direkt(westfriedhof,gern,u1).",
			"direkt(gern,rotkreuzplatz,u1).",
			"direkt(rotkreuzplatz,maillingerstrasse,u1).",
			"direkt(maillingerstrasse,stiglmaierplatz,u1).",
			"direkt(stiglmaierplatz, hauptbahnhof,u1).",
			"direkt(hauptbahnhof,sendlinger_tor,u1).",
			"direkt(sendlinger_tor,fraunhoferstrasse,u1).",
			"direkt(fraunhoferstrasse,kolumbusplatz,u1).",
			"direkt(kolumbusplatz,candidplatz,u1).",
			"direkt(candidplatz,wettersteinplatz,u1).",
			"direkt(wettersteinplatz,st_quirin_platz,u1).",
			"direkt(st_quirin_platz,mangfallplatz,u1).",
			"% U2",
			"direkt(feldmoching,hasenbergl,u2).",
			"direkt(hasenbergl,duelferstrasse,u2).",
			"direkt(duelferstrasse,harthof,u2).",
			"direkt(harthof,am_hart,u2).",
			"direkt(am_hart,frankfurter_ring,u2).",
			"direkt(frankfurter_ring,milbertshofen,u2).",
			"direkt(milbertshofen,scheidplatz,u2).",
			"direkt(scheidplatz,hohenzollernplatz,u2).",
			"direkt(hohenzollernplatz,josephsplatz,u2).",
			"direkt(josephsplatz,theresienstrasse,u2).",
			"direkt(theresienstrasse,koenigsplatz,u2).",
			"direkt(koenigsplatz,hauptbahnhof,u2).",
			"direkt(hauptbahnhof,sendlinger_tor,u2).",
			"direkt(sendlinger_tor,fraunhoferstrasse,u2).",
			"direkt(fraunhoferstrasse,kolumbusplatz,u2).",
			"direkt(kolumbusplatz,silberhornstrasse,u2).",
			"direkt(silberhornstrasse,unterbergstrasse,u2).",
			"direkt(unterbergstrasse,giesing,u2).",
			"direkt(giesing,karl_preis_platz,u2).",
			"direkt(karl_preis_platz,innsbrucker_ring,u2).",
			"direkt(innsbrucker_ring,josephsburg,u2).",
			"direkt(josephsburg,kreillerstrasse,u2).",
			"direkt(kreillerstrasse,trudering,u2).",
			"direkt(trudering,moosfeld,u2).",
			"direkt(moosfeld,messestadt_west,u2).",
			"direkt(messestadt_west,messestadt_ost,u2).",
			"% U3",
			"direkt(moosach,moosacher_st_martins_platz,u3).",
			"direkt(moosacher_st_martins_platz,olympia_einkaufszentrum,u3).",
			"direkt(olympia_einkaufszentrum,oberwiesenfeld,u3).",
			"direkt(oberwiesenfeld,olympiazentrum,u3).",
			"direkt(olympiazentrum,petuelring,u3).",
			"direkt(petuelring,scheidplatz,u3).",
			"direkt(scheidplatz,bonner_platz,u3).",
			"direkt(bonner_platz,muenchner_freiheit,u3).",
			"direkt(muenchner_freiheit,giselastrasse,u3).",
			"direkt(giselastrasse,universitaet,u3).",
			"direkt(universitaet,odeonsplatz,u3).",
			"direkt(odeonsplatz,marienplatz,u3).",
			"direkt(marienplatz,sendlinger_tor,u3).",
			"direkt(sendlinger_tor,goetheplatz,u3).",
			"direkt(goetheplatz,poccistrasse,u3).",
			"direkt(poccistrasse,implerstrasse,u3).",
			"direkt(implerstrasse,brudermuehlstrasse,u3).",
			"direkt(brudermuehlstrasse,thalkirchen,u3).",
			"direkt(thalkirchen,obersendling,u3).",
			"direkt(obersendling,aidenbachstrasse,u3).",
			"direkt(aidenbachstrasse,machtlfinger_strasse,u3).",
			"direkt(machtlfinger_strasse,forstenrieder_allee,u3).",
			"direkt(forstenrieder_allee,basler_str,u3).",
			"direkt(basler_str,forstenried_west,u3).",
			"% U4",
			"direkt(westendstrasse,heimeranplatz,u4).",
			"direkt(heimeranplatz,schwanthalerhoehe,u4).",
			"direkt(schwanthalerhoehe,theresienwiese,u4).",
			"direkt(theresienwiese,hauptbahnhof,u4).",
			"direkt(hauptbahnhof,karlsplatz,u4).",
			"direkt(karlsplatz,odeonsplatz,u4).",
			"direkt(odeonsplatz,lehel,u4).",
			"direkt(lehel,max_weber_platz,u4).",
			"direkt(max_weber_platz,prinzregentenplatz,u4).",
			"direkt(prinzregentenplatz,boehmerwaldplatz,u4).",
			"direkt(boehmerwaldplatz,richard_strauss_strasse,u4).",
			"direkt(richard_strauss_strasse,arabellapark,u4).",
			"% U5",
			"direkt(laimer_platz,friedenheimer_strasse,u5).",
			"direkt(friedenheimer_strasse,westendstrasse,u5).",
			"direkt(westendstrasse,heimeranplatz,u5).",
			"direkt(heimeranplatz,schwanthalerhoehe,u5).",
			"direkt(schwanthalerhoehe,theresienwiese,u5).",
			"direkt(theresienwiese,hauptbahnhof,u5).",
			"direkt(hauptbahnhof,karlsplatz,u5).",
			"direkt(karlsplatz,odeonsplatz,u5).",
			"direkt(odeonsplatz,lehel,u5).",
			"direkt(lehel,max_weber_platz,u5).",
			"direkt(max_weber_platz,ostbahnhof,u5).",
			"direkt(ostbahnhof,innsbrucker_ring,u5).",
			"direkt(innsbrucker_ring,michelibad,u5).",
			"direkt(michelibad,quiddestrasse,u5).",
			"direkt(quiddestrasse,neuperlach_zentrum,u5).",
			"direkt(neuperlach_zentrum,therese_giehse_allee,u5).",
			"direkt(therese_giehse_allee,neuperlach_sued,u5).",
			"% U6",
			"direkt(garching_forschungszentrum,garching,u6).",
			"direkt(garching,garching_hochbrueck,u6).",
			"direkt(garching_hochbrueck,froettmanning,u6).",
			"direkt(froettmanning,kieferngarten,u6).",
			"direkt(kieferngarten,freimann,u6).",
			"direkt(freimann,studentenstadt,u6).",
			"direkt(studentenstadt,alte_heide,u6).",
			"direkt(alte_heide,nordfriedhof,u6).",
			"direkt(nordfriedhof,dietlindenstrasse,u6).",
			"direkt(dietlindenstrasse,muenchner_freiheit,u6).",
			"direkt(muenchner_freiheit,giselastrasse,u6).",
			"direkt(giselastrasse,universitaet,u6).",
			"direkt(universitaet,odeonsplatz,u6).",
			"direkt(odeonsplatz,marienplatz,u6).",
			"direkt(marienplatz,sendlinger_tor,u6).",
			"direkt(sendlinger_tor,goetheplatz,u6).",
			"direkt(goetheplatz,poccistrasse,u6).",
			"direkt(poccistrasse,implerstrasse,u6).",
			"direkt(implerstrasse,harras,u6).",
			"direkt(harras,partnachplatz,u6).",
			"direkt(partnachplatz,westpark,u6).",
			"direkt(westpark,holzapfelkreuth,u6).",
			"direkt(holzapfelkreuth,haderner_stern,u6).",
			"direkt(haderner_stern,grosshadern,u6).",
			"direkt(grosshadern,klinikum_grosshadern,u6).",
			"bidirekt(V,N,L) :- direkt(V,N,L).",
			"bidirekt(V,N,L) :- direkt(N,V,L).",
			"bidirekt(A,B,L) :- bidirekt(A,X,L),bidirekt(X,B,L).",
			"",
			"indirekt(V,N) :- bidirekt(V,N,_).",
			"indirekt(V,N) :- bidirekt(V,X,_),indirekt(X,N), N\\=V."
		],
		"query": "indirekt(garching,trudering)"
	},
	{
		"name": "Muencher U-Bahn (U2 und U6)",
		"description": "Teile des Muenchner U-Bahn-Netzes.",
		"source": "",
		"ruleset": [
			"% Fakten (Linien U2 und U6)",
			"direkt(feldmoching,hasenbergl,u2).",
			"direkt(hasenbergl,duelferstrasse,u2).",
			"direkt(duelferstrasse,harthof,u2).",
			"direkt(harthof,am_hart,u2).",
			"direkt(am_hart,frankfurter_ring,u2).",
			"direkt(frankfurter_ring,milbertshofen,u2).",
			"direkt(milbertshofen,scheidplatz,u2).",
			"direkt(scheidplatz,hohenzollernplatz,u2).",
			"direkt(hohenzollernplatz,josephsplatz,u2).",
			"direkt(josephsplatz,theresienstrasse,u2).",
			"direkt(theresienstrasse,koenigsplatz,u2).",
			"direkt(koenigsplatz,hauptbahnhof,u2).",
			"direkt(hauptbahnhof,sendlinger_tor,u2).",
			"direkt(sendlinger_tor,fraunhoferstrasse,u2).",
			"direkt(fraunhoferstrasse,kolumbusplatz,u2).",
			"direkt(kolumbusplatz,silberhornstrasse,u2).",
			"direkt(silberhornstrasse,unterbergstrasse,u2).",
			"direkt(unterbergstrasse,giesing,u2).",
			"direkt(giesing,karl_preis_platz,u2).",
			"direkt(karl_preis_platz,innsbrucker_ring,u2).",
			"direkt(innsbrucker_ring,josephsburg,u2).",
			"direkt(josephsburg,kreillerstrasse,u2).",
			"direkt(kreillerstrasse,trudering,u2).",
			"direkt(trudering,moosfeld,u2).",
			"direkt(moosfeld,messestadt_west,u2).",
			"direkt(messestadt_west,messestadt_ost,u2).",
			"",
			"direkt(garching_forschungszentrum,garching,u6).",
			"direkt(garching,garching_hochbrueck,u6).",
			"direkt(garching_hochbrueck,froettmanning,u6).",
			"direkt(froettmanning,kieferngarten,u6).", 
			"direkt(kieferngarten,freimann,u6).",
			"direkt(freimann,studentenstadt,u6).", 
			"direkt(studentenstadt,alte_heide,u6).", 
			"direkt(alte_heide,nordfriedhof,u6).",
			"direkt(nordfriedhof,dietlindenstrasse,u6).",
			"direkt(dietlindenstrasse,muenchner_freiheit,u6).",
			"direkt(muenchner_freiheit,odeonsplatz,u6).",
			"direkt(odeonsplatz,marienplatz,u6).",
			"direkt(marienplatz,sendlinger_tor,u6).", 
			"direkt(sendlinger_tor,goetheplatz,u6).",
			"direkt(goetheplatz,poccistrasse,u6).",
			"direkt(poccistrasse,implerstrasse,u6).",
			"direkt(implerstrasse,harras,u6).",
			"direkt(harras,partnachplatz,u6).",
			"direkt(partnachplatz,westpark,u6).",
			"direkt(westpark,holzapfelkreuth,u6).",
			"direkt(holzapfelkreuth,haderner_stern,u6).",
			"direkt(haderner_stern,grosshadern,u6).",
			"direkt(grosshadern,klinikum_grosshadern,u6).",
			"",
			"bidirekt(V,N,L) :- direkt(V,N,L).",
			"bidirekt(V,N,L) :- direkt(N,V,L).",
			"bidirekt(A,B,L) :- bidirekt(A,X,L),bidirekt(X,B,L).",
			"",
			"indirekt(V,N) :- bidirekt(V,N,_).",
			"indirekt(V,N) :- bidirekt(V,X,_),indirekt(X,N), N\\=V."
		],
		"query": "indirekt(garching,trudering)"
	},
	{
		"name": "Bauteile",
		"description": "Bauteile von Autos.",
		"source": "",
		"ruleset": [
			"bauteil(auto,1500,kb).",
			"bauteil(fahrgestell,15,ka).",
			"bauteil(b,20,kb).",
			"bauteil(aa,5,kb).",
			"bauteil(ab,5,ka).",
			"bauteil(aaa,1,ka).",
			"bauteil(aab,2,kc).",
			"konstrukteur(ka,phildunphy,1970).",
			"konstrukteur(kb,jaypritchett,1948).",
			"konstrukteur(kc,schmidt,2000).",
			"besteht_aus(auto,fahrgestell).",
			"besteht_aus(fahrgestell,aa,1).",
			"besteht_aus(fahrgestell,ab,1).",
			"besteht_aus(aa,aaa,1).",
			"besteht_aus(aa,aab,1).",
		],
		"query": "bauteil(A,B,C)"
	}
]
